# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fmessenger.proto\"\r\n\x0b\x45mptyStream\"8\n\x03Msg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nfriendname\x18\x03 \x01(\t2M\n\tMessenger\x12!\n\tMsgStream\x12\x0c.EmptyStream\x1a\x04.Msg0\x01\x12\x1d\n\x07SendMsg\x12\x04.Msg\x1a\x0c.EmptyStreamb\x06proto3')
)




_EMPTYSTREAM = _descriptor.Descriptor(
  name='EmptyStream',
  full_name='EmptyStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=32,
)


_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Msg.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Msg.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='friendname', full_name='Msg.friendname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['EmptyStream'] = _EMPTYSTREAM
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyStream = _reflection.GeneratedProtocolMessageType('EmptyStream', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYSTREAM,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:EmptyStream)
  ))
_sym_db.RegisterMessage(EmptyStream)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(
  DESCRIPTOR = _MSG,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:Msg)
  ))
_sym_db.RegisterMessage(Msg)



_MESSENGER = _descriptor.ServiceDescriptor(
  name='Messenger',
  full_name='Messenger',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=92,
  serialized_end=169,
  methods=[
  _descriptor.MethodDescriptor(
    name='MsgStream',
    full_name='Messenger.MsgStream',
    index=0,
    containing_service=None,
    input_type=_EMPTYSTREAM,
    output_type=_MSG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendMsg',
    full_name='Messenger.SendMsg',
    index=1,
    containing_service=None,
    input_type=_MSG,
    output_type=_EMPTYSTREAM,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGER)

DESCRIPTOR.services_by_name['Messenger'] = _MESSENGER

# @@protoc_insertion_point(module_scope)
